version: "3.5"
services:
  db:
    image: postgres:12
    restart: on-failure
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d"
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c '/wait-for.sh db:5432 && /api'
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - api:/data/api
    depends_on:
      - db
    restart: on-failure


volumes:
  postgres:
  api:

