version: "3.5"
services:
  db:
    image: postgres:12
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
    ports:
      - "5432:5432"
    volumes:
      - rundoo:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d"
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c '/wait-for.sh db:5432 && /api'
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - api:/data/api
    depends_on:
      - db
    restart: on-failure
  react:
    build:
      context: ./frontend/randoo
      dockerfile: ./Dockerfile
    command: sh -c 'npm start'
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/randoo:/app
    depends_on:
      - api


volumes:
  rundoo:
  api:
  frontend:

